# Make sure to create a copy of this file and name it bot-settings.toml

debug = false
user_token = "YOUR_DISCORD_ACCOUNT_TOKEN"

# You can see *\src\bot\tasks\__init__.py to know the task_name: str, their preferences {str, {}}, input_data for preference {}
tasks = [
    ["auto_roll", {}],
    ["claim_daily", {}],
    ["claim_kakera", {"always_claim" = {}}],
    ["claim_roll", {"claim_threshold" = {"claim_threshold" = 200}, "use_resets_on_wish_only"= {}, "auto_last_claim"= {}}]
]


# You can get most of this by the mudae $settings command
# Add more channels by copy pasting the entire [[channels_information]]

[[channels_information]]
id = 1111111111111111111 # To be more specific the id of the channel to roll in
max_rolls = 10           # Max roll quantity
prefix = "$"             # The prefix of mudae
command = "mx"           # The command to roll
shifthour = 0            # $shifthour of the server
minute_reset = 40        # The minute where the rolls restart
delay_claim_roll = 40    # The delay for the Roll claims
delay_claim_kakera = 40  # The delay for the kakera claims
# This one varies depending on your kakera loot
rt_max_cd = 72000
dk_max_cd = 72000

max_kakera_power = 110


# Everything inside these arrays/lists is case sensitive
wished_rolls = [
    "Raiden Mei",
    "Zero Two",
    ]
wished_series = [
    "Naruto",
    "Pokedex",
]

# You can specify the kakera type that will be claimed.
# "kakera" means any kakera. if you want this don't change it
# visit https://mudae.fandom.com/wiki/Kakera to see the colors.
# Just add the color initial in uppercase.
# Example:
# wished_kakera = ["kakeraT", "kakeraO"]
wished_kakera = [
    "kakera",
    ]

# You add more channels by copy pasting the entire [[channels_information]]
[[channels_information]]
...
